///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomationSQLdm.QueryPlan
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the QueryPlanRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("425f0314-efb0-4ba1-80d4-752d599c9284")]
    public partial class QueryPlanRepo : RepoGenBaseFolder
    {
        static QueryPlanRepo instance = new QueryPlanRepo();
        QueryPlanRepoFolders.SQLdmDesktopAppFolder _sqldmdesktop;
        QueryPlanRepoFolders.RepoConsoleDialogAppFolder _repoconsoledialog;
        QueryPlanRepoFolders.MonitoredSQLServerPropertiesAppFolder _monitoredsqlserverproperties;

        /// <summary>
        /// Gets the singleton class instance representing the QueryPlanRepo element repository.
        /// </summary>
        [RepositoryFolder("425f0314-efb0-4ba1-80d4-752d599c9284")]
        public static QueryPlanRepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public QueryPlanRepo() 
            : base("QueryPlanRepo", "/", null, 0, false, "425f0314-efb0-4ba1-80d4-752d599c9284", ".\\RepositoryImages\\QueryPlanRepo425f0314.rximgres")
        {
            _sqldmdesktop = new QueryPlanRepoFolders.SQLdmDesktopAppFolder(this);
            _repoconsoledialog = new QueryPlanRepoFolders.RepoConsoleDialogAppFolder(this);
            _monitoredsqlserverproperties = new QueryPlanRepoFolders.MonitoredSQLServerPropertiesAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("425f0314-efb0-4ba1-80d4-752d599c9284")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SQLdmDesktop folder.
        /// </summary>
        [RepositoryFolder("6541cc49-166c-4209-a267-3f050f9794f8")]
        public virtual QueryPlanRepoFolders.SQLdmDesktopAppFolder SQLdmDesktop
        {
            get { return _sqldmdesktop; }
        }

        /// <summary>
        /// The RepoConsoleDialog folder.
        /// </summary>
        [RepositoryFolder("be321ce4-708d-4f77-b46b-9df292a4f756")]
        public virtual QueryPlanRepoFolders.RepoConsoleDialogAppFolder RepoConsoleDialog
        {
            get { return _repoconsoledialog; }
        }

        /// <summary>
        /// The MonitoredSQLServerProperties folder.
        /// </summary>
        [RepositoryFolder("0fe828ef-188b-4726-816b-908ddd4dcbf9")]
        public virtual QueryPlanRepoFolders.MonitoredSQLServerPropertiesAppFolder MonitoredSQLServerProperties
        {
            get { return _monitoredsqlserverproperties; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class QueryPlanRepoFolders
    {
        /// <summary>
        /// The SQLdmDesktopAppFolder folder.
        /// </summary>
        [RepositoryFolder("6541cc49-166c-4209-a267-3f050f9794f8")]
        public partial class SQLdmDesktopAppFolder : RepoGenBaseFolder
        {
            QueryPlanRepoFolders.QueriesTabFolder _queriestab;
            RepoItemInfo _toolsInfo;
            RepoItemInfo _allserversInfo;
            RepoItemInfo _fileInfo;
            RepoItemInfo _tabqueriesInfo;
            RepoItemInfo _btnqueconfigurequerymonitorInfo;

            /// <summary>
            /// Creates a new SQLdmDesktop  folder.
            /// </summary>
            public SQLdmDesktopAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SQLdmDesktop", "/form[@title~'^Idera\\ SQL\\ diagnostic\\ mana']", parentFolder, 30000, null, true, "6541cc49-166c-4209-a267-3f050f9794f8", "")
            {
                _queriestab = new QueryPlanRepoFolders.QueriesTabFolder(this);
                _toolsInfo = new RepoItemInfo(this, "Tools", ".//list[@automationid='toolsMenu']/picture[@automationid='HeaderPresenter']/text[@caption='Tools']", 30000, null, "eb5102cb-9ffe-4187-a21a-7bfb33aeacd0");
                _allserversInfo = new RepoItemInfo(this, "AllServers", ".//statusbar[@automationid='statusBar']/?/?/container[@automationid='navigationPaneHost']/?/?/container[@controlname='NavigationPaneControl']//container[@controlname='serverGroupPanel']/tree[@controlname='userViewTreeView']/treeitem[@accessiblename='All Servers']", 30000, null, "e1dd82b2-0166-4cf7-9332-0b716603424e");
                _fileInfo = new RepoItemInfo(this, "File", ".//list[@automationid='fileMenu']/picture[@automationid='HeaderPresenter']/text[@caption='File']", 30000, null, "8e40f701-63be-4ffb-a947-93ef2ff123bd");
                _tabqueriesInfo = new RepoItemInfo(this, "tabQueries", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Queries']", 30000, null, "7d1ef42b-c90e-43b5-9c73-65b5f3c4864c");
                _btnqueconfigurequerymonitorInfo = new RepoItemInfo(this, "btnQUEConfigureQueryMonitor", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Queries']/toolbar[@automationid='queriesTabPropertiesGroup']/button", 30000, null, "10e61a27-baa0-4838-839d-0d62b5e2739a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6541cc49-166c-4209-a267-3f050f9794f8")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6541cc49-166c-4209-a267-3f050f9794f8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tools item.
            /// </summary>
            [RepositoryItem("eb5102cb-9ffe-4187-a21a-7bfb33aeacd0")]
            public virtual Ranorex.Text Tools
            {
                get
                {
                    return _toolsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Tools item info.
            /// </summary>
            [RepositoryItemInfo("eb5102cb-9ffe-4187-a21a-7bfb33aeacd0")]
            public virtual RepoItemInfo ToolsInfo
            {
                get
                {
                    return _toolsInfo;
                }
            }

            /// <summary>
            /// The AllServers item.
            /// </summary>
            [RepositoryItem("e1dd82b2-0166-4cf7-9332-0b716603424e")]
            public virtual Ranorex.TreeItem AllServers
            {
                get
                {
                    return _allserversInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The AllServers item info.
            /// </summary>
            [RepositoryItemInfo("e1dd82b2-0166-4cf7-9332-0b716603424e")]
            public virtual RepoItemInfo AllServersInfo
            {
                get
                {
                    return _allserversInfo;
                }
            }

            /// <summary>
            /// The File item.
            /// </summary>
            [RepositoryItem("8e40f701-63be-4ffb-a947-93ef2ff123bd")]
            public virtual Ranorex.Text File
            {
                get
                {
                    return _fileInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The File item info.
            /// </summary>
            [RepositoryItemInfo("8e40f701-63be-4ffb-a947-93ef2ff123bd")]
            public virtual RepoItemInfo FileInfo
            {
                get
                {
                    return _fileInfo;
                }
            }

            /// <summary>
            /// The tabQueries item.
            /// </summary>
            [RepositoryItem("7d1ef42b-c90e-43b5-9c73-65b5f3c4864c")]
            public virtual Ranorex.TabPage tabQueries
            {
                get
                {
                    return _tabqueriesInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The tabQueries item info.
            /// </summary>
            [RepositoryItemInfo("7d1ef42b-c90e-43b5-9c73-65b5f3c4864c")]
            public virtual RepoItemInfo tabQueriesInfo
            {
                get
                {
                    return _tabqueriesInfo;
                }
            }

            /// <summary>
            /// The btnQUEConfigureQueryMonitor item.
            /// </summary>
            [RepositoryItem("10e61a27-baa0-4838-839d-0d62b5e2739a")]
            public virtual Ranorex.Button btnQUEConfigureQueryMonitor
            {
                get
                {
                    return _btnqueconfigurequerymonitorInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnQUEConfigureQueryMonitor item info.
            /// </summary>
            [RepositoryItemInfo("10e61a27-baa0-4838-839d-0d62b5e2739a")]
            public virtual RepoItemInfo btnQUEConfigureQueryMonitorInfo
            {
                get
                {
                    return _btnqueconfigurequerymonitorInfo;
                }
            }

            /// <summary>
            /// The QueriesTab folder.
            /// </summary>
            [RepositoryFolder("64c37e8e-659a-4860-84fa-de6871ac5cef")]
            public virtual QueryPlanRepoFolders.QueriesTabFolder QueriesTab
            {
                get { return _queriestab; }
            }
        }

        /// <summary>
        /// The QueriesTabFolder folder.
        /// </summary>
        [RepositoryFolder("64c37e8e-659a-4860-84fa-de6871ac5cef")]
        public partial class QueriesTabFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rgquesignaturemodeInfo;

            /// <summary>
            /// Creates a new QueriesTab  folder.
            /// </summary>
            public QueriesTabFolder(RepoGenBaseFolder parentFolder) :
                    base("QueriesTab", ".//toolbar[@automationid='ribbon']/tabpage[@automationid='Queries']/toolbar[@automationid='queriesTabViewsGroup']", parentFolder, 30000, null, false, "64c37e8e-659a-4860-84fa-de6871ac5cef", "")
            {
                _rgquesignaturemodeInfo = new RepoItemInfo(this, "rgQUESignatureMode", ".//container[@caption='']/radiobutton[1]", 30000, null, "591cb34e-b127-48c5-9092-d5a85fa05f1b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("64c37e8e-659a-4860-84fa-de6871ac5cef")]
            public virtual Ranorex.ToolBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ToolBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("64c37e8e-659a-4860-84fa-de6871ac5cef")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The rgQUESignatureMode item.
            /// </summary>
            [RepositoryItem("591cb34e-b127-48c5-9092-d5a85fa05f1b")]
            public virtual Ranorex.RadioButton rgQUESignatureMode
            {
                get
                {
                    return _rgquesignaturemodeInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rgQUESignatureMode item info.
            /// </summary>
            [RepositoryItemInfo("591cb34e-b127-48c5-9092-d5a85fa05f1b")]
            public virtual RepoItemInfo rgQUESignatureModeInfo
            {
                get
                {
                    return _rgquesignaturemodeInfo;
                }
            }
        }

        /// <summary>
        /// The RepoConsoleDialogAppFolder folder.
        /// </summary>
        [RepositoryFolder("be321ce4-708d-4f77-b46b-9df292a4f756")]
        public partial class RepoConsoleDialogAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnrcdconnectInfo;

            /// <summary>
            /// Creates a new RepoConsoleDialog  folder.
            /// </summary>
            public RepoConsoleDialogAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RepoConsoleDialog", "//form[@controlname='RepositoryConnectionDialog']", parentFolder, 30000, null, true, "be321ce4-708d-4f77-b46b-9df292a4f756", "")
            {
                _btnrcdconnectInfo = new RepoItemInfo(this, "btnRCDConnect", ".//button[@controlname='connectButton']", 30000, null, "4df3169e-e17e-4a01-85a9-2197d51fe193");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("be321ce4-708d-4f77-b46b-9df292a4f756")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("be321ce4-708d-4f77-b46b-9df292a4f756")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnRCDConnect item.
            /// </summary>
            [RepositoryItem("4df3169e-e17e-4a01-85a9-2197d51fe193")]
            public virtual Ranorex.Button btnRCDConnect
            {
                get
                {
                    return _btnrcdconnectInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnRCDConnect item info.
            /// </summary>
            [RepositoryItemInfo("4df3169e-e17e-4a01-85a9-2197d51fe193")]
            public virtual RepoItemInfo btnRCDConnectInfo
            {
                get
                {
                    return _btnrcdconnectInfo;
                }
            }
        }

        /// <summary>
        /// The MonitoredSQLServerPropertiesAppFolder folder.
        /// </summary>
        [RepositoryFolder("0fe828ef-188b-4726-816b-908ddd4dcbf9")]
        public partial class MonitoredSQLServerPropertiesAppFolder : RepoGenBaseFolder
        {
            QueryPlanRepoFolders.PnlQueryMonitorFolder _pnlquerymonitor;
            QueryPlanRepoFolders.PnlPoorlyPerformingFolder _pnlpoorlyperforming;
            RepoItemInfo _btnmsspokInfo;
            RepoItemInfo _btnmsspcancelInfo;

            /// <summary>
            /// Creates a new MonitoredSQLServerProperties  folder.
            /// </summary>
            public MonitoredSQLServerPropertiesAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MonitoredSQLServerProperties", "//form[@controlname='MonitoredSqlServerInstancePropertiesDialog']", parentFolder, 30000, null, true, "0fe828ef-188b-4726-816b-908ddd4dcbf9", "")
            {
                _pnlquerymonitor = new QueryPlanRepoFolders.PnlQueryMonitorFolder(this);
                _pnlpoorlyperforming = new QueryPlanRepoFolders.PnlPoorlyPerformingFolder(this);
                _btnmsspokInfo = new RepoItemInfo(this, "btnMSSPOk", ".//button[@controlname='okButton']", 30000, null, "13b47ba1-9cc6-4d2e-9ad7-55fd1cf97087");
                _btnmsspcancelInfo = new RepoItemInfo(this, "btnMSSPCancel", ".//button[@controlname='cancelButton']", 30000, null, "a943eb34-0451-44cf-82b4-d0dde07eaeec");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0fe828ef-188b-4726-816b-908ddd4dcbf9")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0fe828ef-188b-4726-816b-908ddd4dcbf9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnMSSPOk item.
            /// </summary>
            [RepositoryItem("13b47ba1-9cc6-4d2e-9ad7-55fd1cf97087")]
            public virtual Ranorex.Button btnMSSPOk
            {
                get
                {
                    return _btnmsspokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnMSSPOk item info.
            /// </summary>
            [RepositoryItemInfo("13b47ba1-9cc6-4d2e-9ad7-55fd1cf97087")]
            public virtual RepoItemInfo btnMSSPOkInfo
            {
                get
                {
                    return _btnmsspokInfo;
                }
            }

            /// <summary>
            /// The btnMSSPCancel item.
            /// </summary>
            [RepositoryItem("a943eb34-0451-44cf-82b4-d0dde07eaeec")]
            public virtual Ranorex.Button btnMSSPCancel
            {
                get
                {
                    return _btnmsspcancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnMSSPCancel item info.
            /// </summary>
            [RepositoryItemInfo("a943eb34-0451-44cf-82b4-d0dde07eaeec")]
            public virtual RepoItemInfo btnMSSPCancelInfo
            {
                get
                {
                    return _btnmsspcancelInfo;
                }
            }

            /// <summary>
            /// The pnlQueryMonitor folder.
            /// </summary>
            [RepositoryFolder("522c64dd-76cf-4f3d-92c1-1d797f12e106")]
            public virtual QueryPlanRepoFolders.PnlQueryMonitorFolder pnlQueryMonitor
            {
                get { return _pnlquerymonitor; }
            }

            /// <summary>
            /// The pnlPoorlyPerforming folder.
            /// </summary>
            [RepositoryFolder("53519678-5c76-4a2f-8537-22eb978ce062")]
            public virtual QueryPlanRepoFolders.PnlPoorlyPerformingFolder pnlPoorlyPerforming
            {
                get { return _pnlpoorlyperforming; }
            }
        }

        /// <summary>
        /// The PnlQueryMonitorFolder folder.
        /// </summary>
        [RepositoryFolder("522c64dd-76cf-4f3d-92c1-1d797f12e106")]
        public partial class PnlQueryMonitorFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rgcqdusingquerystoreInfo;
            RepoItemInfo _rgcqdusingextendedeventsInfo;
            RepoItemInfo _rgcqdusingtraceInfo;
            RepoItemInfo _cbcollectactualqueryplansInfo;
            RepoItemInfo _cbcollectestimatedqueryplansInfo;
            RepoItemInfo _cbmsspenablequerymonitorInfo;

            /// <summary>
            /// Creates a new pnlQueryMonitor  folder.
            /// </summary>
            public PnlQueryMonitorFolder(RepoGenBaseFolder parentFolder) :
                    base("pnlQueryMonitor", ".//container[@controlname='propertiesControl']//container[@controlname='queryMonitorPropertyPage']", parentFolder, 30000, null, false, "522c64dd-76cf-4f3d-92c1-1d797f12e106", "")
            {
                _rgcqdusingquerystoreInfo = new RepoItemInfo(this, "rgCQDUsingQueryStore", ".//container[@controlname='tableLayoutPanel19']/radiobutton[@controlname='rButtonUseQueryStore']", 30000, null, "86342f0c-f63e-4805-82c0-16926a4534dd");
                _rgcqdusingextendedeventsInfo = new RepoItemInfo(this, "rgCQDUsingExtendedEvents", ".//container[@controlname='tableLayoutPanel19']/radiobutton[@controlname='rButtonUseExtendedEvents']", 30000, null, "2684fc45-e00b-4db1-b18d-f18ccb47b9fe");
                _rgcqdusingtraceInfo = new RepoItemInfo(this, "rgCQDUsingTrace", ".//container[@controlname='tableLayoutPanel19']/radiobutton[@controlname='rButtonUseTrace']", 30000, null, "f9d05d15-4ca4-48a2-97db-a9b6e51607f1");
                _cbcollectactualqueryplansInfo = new RepoItemInfo(this, "cbCollectActualQueryPlans", ".//container[@controlname='tableLayoutPanel19']/checkbox[@controlname='chkCollectQueryPlans']", 30000, null, "a6ff82fd-1d86-4797-af10-0e33ae80411f");
                _cbcollectestimatedqueryplansInfo = new RepoItemInfo(this, "cbCollectEstimatedQueryPlans", ".//container[@controlname='tableLayoutPanel19']/checkbox[@controlname='chkCollectEstimatedQueryPlans']", 30000, null, "174b46fd-671a-4166-ade6-60932113577b");
                _cbmsspenablequerymonitorInfo = new RepoItemInfo(this, "cbMSSPEnableQueryMonitor", ".//container[@controlname='tableLayoutPanel17']/checkbox[@controlname='enableQueryMonitorTraceCheckBox']", 30000, null, "f08702af-39df-45fc-a33c-286f1d10133b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("522c64dd-76cf-4f3d-92c1-1d797f12e106")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("522c64dd-76cf-4f3d-92c1-1d797f12e106")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The rgCQDUsingQueryStore item.
            /// </summary>
            [RepositoryItem("86342f0c-f63e-4805-82c0-16926a4534dd")]
            public virtual Ranorex.RadioButton rgCQDUsingQueryStore
            {
                get
                {
                    return _rgcqdusingquerystoreInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rgCQDUsingQueryStore item info.
            /// </summary>
            [RepositoryItemInfo("86342f0c-f63e-4805-82c0-16926a4534dd")]
            public virtual RepoItemInfo rgCQDUsingQueryStoreInfo
            {
                get
                {
                    return _rgcqdusingquerystoreInfo;
                }
            }

            /// <summary>
            /// The rgCQDUsingExtendedEvents item.
            /// </summary>
            [RepositoryItem("2684fc45-e00b-4db1-b18d-f18ccb47b9fe")]
            public virtual Ranorex.RadioButton rgCQDUsingExtendedEvents
            {
                get
                {
                    return _rgcqdusingextendedeventsInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rgCQDUsingExtendedEvents item info.
            /// </summary>
            [RepositoryItemInfo("2684fc45-e00b-4db1-b18d-f18ccb47b9fe")]
            public virtual RepoItemInfo rgCQDUsingExtendedEventsInfo
            {
                get
                {
                    return _rgcqdusingextendedeventsInfo;
                }
            }

            /// <summary>
            /// The rgCQDUsingTrace item.
            /// </summary>
            [RepositoryItem("f9d05d15-4ca4-48a2-97db-a9b6e51607f1")]
            public virtual Ranorex.RadioButton rgCQDUsingTrace
            {
                get
                {
                    return _rgcqdusingtraceInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rgCQDUsingTrace item info.
            /// </summary>
            [RepositoryItemInfo("f9d05d15-4ca4-48a2-97db-a9b6e51607f1")]
            public virtual RepoItemInfo rgCQDUsingTraceInfo
            {
                get
                {
                    return _rgcqdusingtraceInfo;
                }
            }

            /// <summary>
            /// The cbCollectActualQueryPlans item.
            /// </summary>
            [RepositoryItem("a6ff82fd-1d86-4797-af10-0e33ae80411f")]
            public virtual Ranorex.CheckBox cbCollectActualQueryPlans
            {
                get
                {
                    return _cbcollectactualqueryplansInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The cbCollectActualQueryPlans item info.
            /// </summary>
            [RepositoryItemInfo("a6ff82fd-1d86-4797-af10-0e33ae80411f")]
            public virtual RepoItemInfo cbCollectActualQueryPlansInfo
            {
                get
                {
                    return _cbcollectactualqueryplansInfo;
                }
            }

            /// <summary>
            /// The cbCollectEstimatedQueryPlans item.
            /// </summary>
            [RepositoryItem("174b46fd-671a-4166-ade6-60932113577b")]
            public virtual Ranorex.CheckBox cbCollectEstimatedQueryPlans
            {
                get
                {
                    return _cbcollectestimatedqueryplansInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The cbCollectEstimatedQueryPlans item info.
            /// </summary>
            [RepositoryItemInfo("174b46fd-671a-4166-ade6-60932113577b")]
            public virtual RepoItemInfo cbCollectEstimatedQueryPlansInfo
            {
                get
                {
                    return _cbcollectestimatedqueryplansInfo;
                }
            }

            /// <summary>
            /// The cbMSSPEnableQueryMonitor item.
            /// </summary>
            [RepositoryItem("f08702af-39df-45fc-a33c-286f1d10133b")]
            public virtual Ranorex.CheckBox cbMSSPEnableQueryMonitor
            {
                get
                {
                    return _cbmsspenablequerymonitorInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The cbMSSPEnableQueryMonitor item info.
            /// </summary>
            [RepositoryItemInfo("f08702af-39df-45fc-a33c-286f1d10133b")]
            public virtual RepoItemInfo cbMSSPEnableQueryMonitorInfo
            {
                get
                {
                    return _cbmsspenablequerymonitorInfo;
                }
            }
        }

        /// <summary>
        /// The PnlPoorlyPerformingFolder folder.
        /// </summary>
        [RepositoryFolder("53519678-5c76-4a2f-8537-22eb978ce062")]
        public partial class PnlPoorlyPerformingFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtppdurationInfo;
            RepoItemInfo _txtpplogicaldiskreadsInfo;
            RepoItemInfo _txtppcpuusageInfo;
            RepoItemInfo _txtppphysicaldiskwritesInfo;
            RepoItemInfo _txtppqueryplanInfo;
            RepoItemInfo _ddlppplansbyInfo;

            /// <summary>
            /// Creates a new pnlPoorlyPerforming  folder.
            /// </summary>
            public PnlPoorlyPerformingFolder(RepoGenBaseFolder parentFolder) :
                    base("pnlPoorlyPerforming", ".//container[@controlname='propertiesControl']//container[@controlname='tableLayoutPanel16']/container[@controlname='fmePoorlyPerformingThresholds']", parentFolder, 30000, null, false, "53519678-5c76-4a2f-8537-22eb978ce062", "")
            {
                _txtppdurationInfo = new RepoItemInfo(this, "txtPPDuration", ".//container[@controlname='durationThresholdSpinner']/text[@controlname='upDownEdit']", 30000, null, "e987797f-ecff-47ac-881f-3b4c10bd04a9");
                _txtpplogicaldiskreadsInfo = new RepoItemInfo(this, "txtPPLogicalDiskReads", ".//container[@controlname='logicalReadsThresholdSpinner']/text[@controlname='upDownEdit']", 30000, null, "91a6652d-e929-4b3f-80c7-3e10f2ff7250");
                _txtppcpuusageInfo = new RepoItemInfo(this, "txtPPCPUUsage", ".//container[@controlname='cpuThresholdSpinner']/text[@controlname='upDownEdit']", 30000, null, "ac2a74df-b58f-435f-9968-53227f66f0c0");
                _txtppphysicaldiskwritesInfo = new RepoItemInfo(this, "txtPPPhysicalDiskWrites", ".//container[@controlname='physicalWritesThresholdSpinner']/text[@controlname='upDownEdit']", 30000, null, "ff7b6a58-395a-411c-af8a-e8471c18dd0a");
                _txtppqueryplanInfo = new RepoItemInfo(this, "txtPPQueryPlan", ".//container[@controlname='topPlanSpinner']/text[@controlname='upDownEdit']", 30000, null, "5acdce90-a84c-41d4-ae66-dff16e260784");
                _ddlppplansbyInfo = new RepoItemInfo(this, "ddlPPPlansBy", ".//element[@controlname='topPlanComboBox']/combobox[@accessiblename='Plans by ']/combobox[@accessiblerole='ComboBox']", 30000, null, "effa3ba9-fec7-4d8d-b111-ed7ad8576798");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("53519678-5c76-4a2f-8537-22eb978ce062")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("53519678-5c76-4a2f-8537-22eb978ce062")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txtPPDuration item.
            /// </summary>
            [RepositoryItem("e987797f-ecff-47ac-881f-3b4c10bd04a9")]
            public virtual Ranorex.Text txtPPDuration
            {
                get
                {
                    return _txtppdurationInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtPPDuration item info.
            /// </summary>
            [RepositoryItemInfo("e987797f-ecff-47ac-881f-3b4c10bd04a9")]
            public virtual RepoItemInfo txtPPDurationInfo
            {
                get
                {
                    return _txtppdurationInfo;
                }
            }

            /// <summary>
            /// The txtPPLogicalDiskReads item.
            /// </summary>
            [RepositoryItem("91a6652d-e929-4b3f-80c7-3e10f2ff7250")]
            public virtual Ranorex.Text txtPPLogicalDiskReads
            {
                get
                {
                    return _txtpplogicaldiskreadsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtPPLogicalDiskReads item info.
            /// </summary>
            [RepositoryItemInfo("91a6652d-e929-4b3f-80c7-3e10f2ff7250")]
            public virtual RepoItemInfo txtPPLogicalDiskReadsInfo
            {
                get
                {
                    return _txtpplogicaldiskreadsInfo;
                }
            }

            /// <summary>
            /// The txtPPCPUUsage item.
            /// </summary>
            [RepositoryItem("ac2a74df-b58f-435f-9968-53227f66f0c0")]
            public virtual Ranorex.Text txtPPCPUUsage
            {
                get
                {
                    return _txtppcpuusageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtPPCPUUsage item info.
            /// </summary>
            [RepositoryItemInfo("ac2a74df-b58f-435f-9968-53227f66f0c0")]
            public virtual RepoItemInfo txtPPCPUUsageInfo
            {
                get
                {
                    return _txtppcpuusageInfo;
                }
            }

            /// <summary>
            /// The txtPPPhysicalDiskWrites item.
            /// </summary>
            [RepositoryItem("ff7b6a58-395a-411c-af8a-e8471c18dd0a")]
            public virtual Ranorex.Text txtPPPhysicalDiskWrites
            {
                get
                {
                    return _txtppphysicaldiskwritesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtPPPhysicalDiskWrites item info.
            /// </summary>
            [RepositoryItemInfo("ff7b6a58-395a-411c-af8a-e8471c18dd0a")]
            public virtual RepoItemInfo txtPPPhysicalDiskWritesInfo
            {
                get
                {
                    return _txtppphysicaldiskwritesInfo;
                }
            }

            /// <summary>
            /// The txtPPQueryPlan item.
            /// </summary>
            [RepositoryItem("5acdce90-a84c-41d4-ae66-dff16e260784")]
            public virtual Ranorex.Text txtPPQueryPlan
            {
                get
                {
                    return _txtppqueryplanInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtPPQueryPlan item info.
            /// </summary>
            [RepositoryItemInfo("5acdce90-a84c-41d4-ae66-dff16e260784")]
            public virtual RepoItemInfo txtPPQueryPlanInfo
            {
                get
                {
                    return _txtppqueryplanInfo;
                }
            }

            /// <summary>
            /// The ddlPPPlansBy item.
            /// </summary>
            [RepositoryItem("effa3ba9-fec7-4d8d-b111-ed7ad8576798")]
            public virtual Ranorex.ComboBox ddlPPPlansBy
            {
                get
                {
                    return _ddlppplansbyInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ddlPPPlansBy item info.
            /// </summary>
            [RepositoryItemInfo("effa3ba9-fec7-4d8d-b111-ed7ad8576798")]
            public virtual RepoItemInfo ddlPPPlansByInfo
            {
                get
                {
                    return _ddlppplansbyInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}