///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomationSQLdm.Grooming_Modifications
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the GroomingRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("16a56f01-8f73-4e50-8864-86e658161df7")]
    public partial class GroomingRepo : RepoGenBaseFolder
    {
        static GroomingRepo instance = new GroomingRepo();
        GroomingRepoFolders.ApplicationAppFolder _application;
        GroomingRepoFolders.GroomingOptionWindowAppFolder _groomingoptionwindow;
        GroomingRepoFolders.SQLdmDCAppFolder _sqldmdc;
        GroomingRepoFolders.DeleteConfirmWindowAppFolder _deleteconfirmwindow;
        GroomingRepoFolders.ManageServersDialogAppFolder _manageserversdialog;
        GroomingRepoFolders.AddServersWizardDialogAppFolder _addserverswizarddialog;
        GroomingRepoFolders.ExceptionMessageBoxFormAppFolder _exceptionmessageboxform;

        /// <summary>
        /// Gets the singleton class instance representing the GroomingRepo element repository.
        /// </summary>
        [RepositoryFolder("16a56f01-8f73-4e50-8864-86e658161df7")]
        public static GroomingRepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public GroomingRepo() 
            : base("GroomingRepo", "/", null, 0, false, "16a56f01-8f73-4e50-8864-86e658161df7", ".\\RepositoryImages\\GroomingRepo16a56f01.rximgres")
        {
            _application = new GroomingRepoFolders.ApplicationAppFolder(this);
            _groomingoptionwindow = new GroomingRepoFolders.GroomingOptionWindowAppFolder(this);
            _sqldmdc = new GroomingRepoFolders.SQLdmDCAppFolder(this);
            _deleteconfirmwindow = new GroomingRepoFolders.DeleteConfirmWindowAppFolder(this);
            _manageserversdialog = new GroomingRepoFolders.ManageServersDialogAppFolder(this);
            _addserverswizarddialog = new GroomingRepoFolders.AddServersWizardDialogAppFolder(this);
            _exceptionmessageboxform = new GroomingRepoFolders.ExceptionMessageBoxFormAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("16a56f01-8f73-4e50-8864-86e658161df7")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Application folder.
        /// </summary>
        [RepositoryFolder("6541cc49-166c-4209-a267-3f050f9794f8")]
        public virtual GroomingRepoFolders.ApplicationAppFolder Application
        {
            get { return _application; }
        }

        /// <summary>
        /// The GroomingOptionWindow folder.
        /// </summary>
        [RepositoryFolder("45d6f264-a0b9-4d39-b07c-41e3680e69d5")]
        public virtual GroomingRepoFolders.GroomingOptionWindowAppFolder GroomingOptionWindow
        {
            get { return _groomingoptionwindow; }
        }

        /// <summary>
        /// The SQLdmDC folder.
        /// </summary>
        [RepositoryFolder("256ebeeb-693e-428e-bf76-2222c9b118b1")]
        public virtual GroomingRepoFolders.SQLdmDCAppFolder SQLdmDC
        {
            get { return _sqldmdc; }
        }

        /// <summary>
        /// The DeleteConfirmWindow folder.
        /// </summary>
        [RepositoryFolder("5ce7a0a5-8af2-4e55-bcc3-0bc83cf5fb2f")]
        public virtual GroomingRepoFolders.DeleteConfirmWindowAppFolder DeleteConfirmWindow
        {
            get { return _deleteconfirmwindow; }
        }

        /// <summary>
        /// The ManageServersDialog folder.
        /// </summary>
        [RepositoryFolder("5cc11763-76f2-47b0-a946-09f66e3b0212")]
        public virtual GroomingRepoFolders.ManageServersDialogAppFolder ManageServersDialog
        {
            get { return _manageserversdialog; }
        }

        /// <summary>
        /// The AddServersWizardDialog folder.
        /// </summary>
        [RepositoryFolder("b2b42fbb-af61-4285-9c7b-5b6cad72d3d6")]
        public virtual GroomingRepoFolders.AddServersWizardDialogAppFolder AddServersWizardDialog
        {
            get { return _addserverswizarddialog; }
        }

        /// <summary>
        /// The ExceptionMessageBoxForm folder.
        /// </summary>
        [RepositoryFolder("9999567a-03cb-4278-91cf-451b5ffba7d6")]
        public virtual GroomingRepoFolders.ExceptionMessageBoxFormAppFolder ExceptionMessageBoxForm
        {
            get { return _exceptionmessageboxform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class GroomingRepoFolders
    {
        /// <summary>
        /// The ApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("6541cc49-166c-4209-a267-3f050f9794f8")]
        public partial class ApplicationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _toolsInfo;
            RepoItemInfo _allserversInfo;

            /// <summary>
            /// Creates a new Application  folder.
            /// </summary>
            public ApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Application", "/form[@title~'^Idera\\ SQL\\ diagnostic\\ mana']", parentFolder, 30000, null, true, "6541cc49-166c-4209-a267-3f050f9794f8", "")
            {
                _toolsInfo = new RepoItemInfo(this, "Tools", ".//list[@automationid='toolsMenu']/picture[@automationid='HeaderPresenter']/text[@caption='Tools']", 30000, null, "eb5102cb-9ffe-4187-a21a-7bfb33aeacd0");
                _allserversInfo = new RepoItemInfo(this, "AllServers", ".//statusbar[@automationid='statusBar']/?/?/container[@automationid='navigationPaneHost']/?/?/container[@controlname='NavigationPaneControl']//container[@controlname='serverGroupPanel']/tree[@controlname='userViewTreeView']/?/?/treeitem[@accessiblename='All Servers']", 30000, null, "e1dd82b2-0166-4cf7-9332-0b716603424e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6541cc49-166c-4209-a267-3f050f9794f8")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6541cc49-166c-4209-a267-3f050f9794f8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tools item.
            /// </summary>
            [RepositoryItem("eb5102cb-9ffe-4187-a21a-7bfb33aeacd0")]
            public virtual Ranorex.Text Tools
            {
                get
                {
                    return _toolsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Tools item info.
            /// </summary>
            [RepositoryItemInfo("eb5102cb-9ffe-4187-a21a-7bfb33aeacd0")]
            public virtual RepoItemInfo ToolsInfo
            {
                get
                {
                    return _toolsInfo;
                }
            }

            /// <summary>
            /// The AllServers item.
            /// </summary>
            [RepositoryItem("e1dd82b2-0166-4cf7-9332-0b716603424e")]
            public virtual Ranorex.TreeItem AllServers
            {
                get
                {
                    return _allserversInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The AllServers item info.
            /// </summary>
            [RepositoryItemInfo("e1dd82b2-0166-4cf7-9332-0b716603424e")]
            public virtual RepoItemInfo AllServersInfo
            {
                get
                {
                    return _allserversInfo;
                }
            }
        }

        /// <summary>
        /// The GroomingOptionWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("45d6f264-a0b9-4d39-b07c-41e3680e69d5")]
        public partial class GroomingOptionWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _aggregatetextboxInfo;
            RepoItemInfo _groomforecasttextboxInfo;
            RepoItemInfo _cancelbuttonInfo;
            RepoItemInfo _combineolderdataInfo;
            RepoItemInfo _aggregationincurrenttimeInfo;
            RepoItemInfo _aggregationincurrentgroomingInfo;
            RepoItemInfo _groommetricsandbaselineInfo;
            RepoItemInfo _btngroomnowInfo;
            RepoItemInfo _txtdgcurrentlyrunningstatusInfo;
            RepoItemInfo _txtaggregationcurrentlyrunningInfo;
            RepoItemInfo _txtdgcompletionstatusInfo;
            RepoItemInfo _txtaggregationcompletionstatusInfo;
            RepoItemInfo _btnaggregatenowInfo;
            RepoItemInfo _btngowokInfo;
            RepoItemInfo _btnrefreshInfo;
            RepoItemInfo _btnapplyInfo;
            RepoItemInfo _txtaggregateforecastingdataInfo;
            RepoItemInfo _txtgroomforecastingdataInfo;
            RepoItemInfo _groomstandardmetrixandbaselineInfo;
            RepoItemInfo _aggregatequerydataintoInfo;
            RepoItemInfo _groominactivealertInfo;
            RepoItemInfo _groomprescriptiveanalysisInfo;
            RepoItemInfo _aggregaiononcedailyatInfo;
            RepoItemInfo _groomsessionsqueriesInfo;
            RepoItemInfo _groomchangelogInfo;
            RepoItemInfo _groomingoncedailyatInfo;

            /// <summary>
            /// Creates a new GroomingOptionWindow  folder.
            /// </summary>
            public GroomingOptionWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GroomingOptionWindow", "/form[@controlname='GroomingOptionsDialog']", parentFolder, 30000, null, true, "45d6f264-a0b9-4d39-b07c-41e3680e69d5", "")
            {
                _aggregatetextboxInfo = new RepoItemInfo(this, "AggregateTextbox", ".//container[@controlname='tableLayoutPanel4']/container[@controlname='auditGroomingThresholdNumericUpDown' and @instance='6']/text[@controlname='upDownEdit']", 30000, null, "bb7bc07f-fdce-435d-a9ac-c0a43ae7aa8e");
                _groomforecasttextboxInfo = new RepoItemInfo(this, "GroomForecastTextbox", ".//container[@controlname='tableLayoutPanel4']/container[@controlname='GroomForecastNumericUpDown' and @instance='7']/text[@controlname='upDownEdit']", 30000, null, "628b3592-d551-45fb-ac4c-09da6d84873f");
                _cancelbuttonInfo = new RepoItemInfo(this, "CancelButton", ".//button[@controlname='cancelButton']", 30000, null, "f32922fa-0f10-43c9-bf8b-635762c36ac8");
                _combineolderdataInfo = new RepoItemInfo(this, "CombineOlderData", ".//container[@controlname='groupBox2']/text[@controlname='label15']", 30000, null, "b11a9e64-8b5f-4df3-8bfd-9c6af34e45f8");
                _aggregationincurrenttimeInfo = new RepoItemInfo(this, "AggregationInCurrentTime", ".//container[@controlname='containerPanel']/?/?/container[@controlname='groupBox2']", 30000, null, "4535d7a1-d40a-4b9f-9e94-eff8ebb581df");
                _aggregationincurrentgroomingInfo = new RepoItemInfo(this, "AggregationInCurrentGrooming", ".//container[@controlname='containerPanel']/?/?/container[@controlname='groupBox4']", 30000, null, "0da66b40-2bde-452d-a086-997be0f58733");
                _groommetricsandbaselineInfo = new RepoItemInfo(this, "GroomMetricsAndBaseLine", ".//container[@controlname='tableLayoutPanel4']/container[@controlname='metricsGroomingThresholdNumericUpDown']/text[@controlname='upDownEdit']", 30000, null, "568da058-6b46-49d9-8a3c-26ffa588c095");
                _btngroomnowInfo = new RepoItemInfo(this, "btnGroomNow", ".//button[@controlname='groomNow']", 30000, null, "27a0f4fc-2384-4454-a9e2-f2f63a2b5f2b");
                _txtdgcurrentlyrunningstatusInfo = new RepoItemInfo(this, "txtDGCurrentlyRunningStatus", ".//container[@controlname='containerPanel']/?/?/container[@controlname='groupBox3']/?/?/text[@controlname='currentlyRunning']", 30000, null, "66a4267d-29c1-49c6-9a94-a860640222fd");
                _txtaggregationcurrentlyrunningInfo = new RepoItemInfo(this, "txtAggregationCurrentlyRunning", ".//container[@controlname='containerPanel']/?/?/container[@controlname='groupBox4']/?/?/text[@controlname='aggregationCurrentlyRunning']", 30000, null, "4677c6d9-2dfe-4e15-86c2-e1ac60f07c46");
                _txtdgcompletionstatusInfo = new RepoItemInfo(this, "txtDGCompletionStatus", ".//container[@controlname='containerPanel']/?/?/container[@controlname='groupBox3']/?/?/text[@controlname='completionStatus']", 30000, null, "3004595f-b329-45aa-b366-25d3475fe811");
                _txtaggregationcompletionstatusInfo = new RepoItemInfo(this, "txtAggregationCompletionStatus", ".//container[@controlname='containerPanel']/?/?/container[@controlname='groupBox4']/?/?/text[@controlname='aggregationCompletionStatus']", 30000, null, "2109553c-92b0-45b1-9345-b2f5ad5c1453");
                _btnaggregatenowInfo = new RepoItemInfo(this, "btnAggregateNow", ".//button[@controlname='aggregateNow']", 30000, null, "e76743c4-523b-4dbb-aa6c-eb80898cce48");
                _btngowokInfo = new RepoItemInfo(this, "btnGOWOk", ".//button[@controlname='okButton']", 30000, null, "db6619de-a8c3-448e-9193-8d14f5673a7f");
                _btnrefreshInfo = new RepoItemInfo(this, "btnRefresh", ".//container[@controlname='containerPanel']/?/?/button[@controlname='refresh']", 30000, null, "dede8117-c9cc-4572-b1f4-7c706fe10774");
                _btnapplyInfo = new RepoItemInfo(this, "btnApply", ".//button[@controlname='apply']", 30000, null, "efff6fbd-be15-4e48-b072-07a1abf036e0");
                _txtaggregateforecastingdataInfo = new RepoItemInfo(this, "txtAggregateForecastingData", ".//container[@controlname='tableLayoutPanel4']/container[@controlname='auditGroomingThresholdNumericUpDown' and @instance='6']/text[@controlname='upDownEdit']", 30000, null, "73504de1-d7ad-4305-9f7d-502158b4fd56");
                _txtgroomforecastingdataInfo = new RepoItemInfo(this, "txtGroomForecastingData", ".//container[@controlname='tableLayoutPanel4']/container[@controlname='GroomForecastNumericUpDown' and @instance='7']/text[@controlname='upDownEdit']", 30000, null, "ac2fb595-2226-49f2-9bc1-49617e0f6e66");
                _groomstandardmetrixandbaselineInfo = new RepoItemInfo(this, "GroomStandardMetrixAndBaseline", ".//container[@controlname='tableLayoutPanel4']/container[@controlname='metricsGroomingThresholdNumericUpDown']/text[@controlname='upDownEdit']", 30000, null, "cb98d8c0-d2f4-4450-b009-3532ca0073e0");
                _aggregatequerydataintoInfo = new RepoItemInfo(this, "AggregateQueryDataInto", ".//container[@controlname='tableLayoutPanel4']/container[@controlname='aggregationThresholdNumericUpDown']/text[@controlname='upDownEdit']", 30000, null, "de5fbc57-3a2c-4f81-9e5c-abc2a430930a");
                _groominactivealertInfo = new RepoItemInfo(this, "GroomInactiveAlert", ".//container[@controlname='tableLayoutPanel4']/container[@controlname='alertsGroomingThresholdNumericUpDown']/text[@controlname='upDownEdit']", 30000, null, "3fb2ebda-cce5-4ac4-b199-394653d2665c");
                _groomprescriptiveanalysisInfo = new RepoItemInfo(this, "GroomPrescriptiveAnalysis", ".//container[@controlname='tableLayoutPanel4']/container[@controltypename='NumericUpDown' and @instance='5']/text[@controlname='upDownEdit']", 30000, null, "75d1eb55-600b-44fc-ac08-9fc009910a61");
                _aggregaiononcedailyatInfo = new RepoItemInfo(this, "AggregaionOnceDailyAt", ".//container[@controlname='containerPanel']//container[@controlname='groupBox2']//combobox//text[@accessiblename='Text area']", 30000, null, "0b029e11-c7a7-423e-a20e-586adb6c05cf");
                _groomsessionsqueriesInfo = new RepoItemInfo(this, "GroomSessionsQueries", ".//container[@controlname='tableLayoutPanel4']/container[@controlname='activityGroomingThresholdNumericUpDown']/text[@controlname='upDownEdit']", 30000, null, "8d4e12ef-38a7-4191-8a37-9ebf6461b612");
                _groomchangelogInfo = new RepoItemInfo(this, "GroomChangeLog", ".//container[@controlname='tableLayoutPanel4']/container[@controltypename='NumericUpDown' and @instance='4']/text[@controlname='upDownEdit']", 30000, null, "ee387910-4f33-4868-8ab2-40e6f12661af");
                _groomingoncedailyatInfo = new RepoItemInfo(this, "GroomingOnceDailyAt", ".//container[@controlname='containerPanel']//container[@controlname='groupBox1']//combobox//text[@accessiblename='Text area']", 30000, null, "1c880ec9-e930-4ccc-ace1-fd289843f3a2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("45d6f264-a0b9-4d39-b07c-41e3680e69d5")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("45d6f264-a0b9-4d39-b07c-41e3680e69d5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AggregateTextbox item.
            /// </summary>
            [RepositoryItem("bb7bc07f-fdce-435d-a9ac-c0a43ae7aa8e")]
            public virtual Ranorex.Text AggregateTextbox
            {
                get
                {
                    return _aggregatetextboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AggregateTextbox item info.
            /// </summary>
            [RepositoryItemInfo("bb7bc07f-fdce-435d-a9ac-c0a43ae7aa8e")]
            public virtual RepoItemInfo AggregateTextboxInfo
            {
                get
                {
                    return _aggregatetextboxInfo;
                }
            }

            /// <summary>
            /// The GroomForecastTextbox item.
            /// </summary>
            [RepositoryItem("628b3592-d551-45fb-ac4c-09da6d84873f")]
            public virtual Ranorex.Text GroomForecastTextbox
            {
                get
                {
                    return _groomforecasttextboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The GroomForecastTextbox item info.
            /// </summary>
            [RepositoryItemInfo("628b3592-d551-45fb-ac4c-09da6d84873f")]
            public virtual RepoItemInfo GroomForecastTextboxInfo
            {
                get
                {
                    return _groomforecasttextboxInfo;
                }
            }

            /// <summary>
            /// The CancelButton item.
            /// </summary>
            [RepositoryItem("f32922fa-0f10-43c9-bf8b-635762c36ac8")]
            public virtual Ranorex.Button CancelButton
            {
                get
                {
                    return _cancelbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CancelButton item info.
            /// </summary>
            [RepositoryItemInfo("f32922fa-0f10-43c9-bf8b-635762c36ac8")]
            public virtual RepoItemInfo CancelButtonInfo
            {
                get
                {
                    return _cancelbuttonInfo;
                }
            }

            /// <summary>
            /// The CombineOlderData item.
            /// </summary>
            [RepositoryItem("b11a9e64-8b5f-4df3-8bfd-9c6af34e45f8")]
            public virtual Ranorex.Text CombineOlderData
            {
                get
                {
                    return _combineolderdataInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CombineOlderData item info.
            /// </summary>
            [RepositoryItemInfo("b11a9e64-8b5f-4df3-8bfd-9c6af34e45f8")]
            public virtual RepoItemInfo CombineOlderDataInfo
            {
                get
                {
                    return _combineolderdataInfo;
                }
            }

            /// <summary>
            /// The AggregationInCurrentTime item.
            /// </summary>
            [RepositoryItem("4535d7a1-d40a-4b9f-9e94-eff8ebb581df")]
            public virtual Ranorex.Container AggregationInCurrentTime
            {
                get
                {
                    return _aggregationincurrenttimeInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The AggregationInCurrentTime item info.
            /// </summary>
            [RepositoryItemInfo("4535d7a1-d40a-4b9f-9e94-eff8ebb581df")]
            public virtual RepoItemInfo AggregationInCurrentTimeInfo
            {
                get
                {
                    return _aggregationincurrenttimeInfo;
                }
            }

            /// <summary>
            /// The AggregationInCurrentGrooming item.
            /// </summary>
            [RepositoryItem("0da66b40-2bde-452d-a086-997be0f58733")]
            public virtual Ranorex.Container AggregationInCurrentGrooming
            {
                get
                {
                    return _aggregationincurrentgroomingInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The AggregationInCurrentGrooming item info.
            /// </summary>
            [RepositoryItemInfo("0da66b40-2bde-452d-a086-997be0f58733")]
            public virtual RepoItemInfo AggregationInCurrentGroomingInfo
            {
                get
                {
                    return _aggregationincurrentgroomingInfo;
                }
            }

            /// <summary>
            /// The GroomMetricsAndBaseLine item.
            /// </summary>
            [RepositoryItem("568da058-6b46-49d9-8a3c-26ffa588c095")]
            public virtual Ranorex.Text GroomMetricsAndBaseLine
            {
                get
                {
                    return _groommetricsandbaselineInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The GroomMetricsAndBaseLine item info.
            /// </summary>
            [RepositoryItemInfo("568da058-6b46-49d9-8a3c-26ffa588c095")]
            public virtual RepoItemInfo GroomMetricsAndBaseLineInfo
            {
                get
                {
                    return _groommetricsandbaselineInfo;
                }
            }

            /// <summary>
            /// The btnGroomNow item.
            /// </summary>
            [RepositoryItem("27a0f4fc-2384-4454-a9e2-f2f63a2b5f2b")]
            public virtual Ranorex.Button btnGroomNow
            {
                get
                {
                    return _btngroomnowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnGroomNow item info.
            /// </summary>
            [RepositoryItemInfo("27a0f4fc-2384-4454-a9e2-f2f63a2b5f2b")]
            public virtual RepoItemInfo btnGroomNowInfo
            {
                get
                {
                    return _btngroomnowInfo;
                }
            }

            /// <summary>
            /// The txtDGCurrentlyRunningStatus item.
            /// </summary>
            [RepositoryItem("66a4267d-29c1-49c6-9a94-a860640222fd")]
            public virtual Ranorex.Text txtDGCurrentlyRunningStatus
            {
                get
                {
                    return _txtdgcurrentlyrunningstatusInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtDGCurrentlyRunningStatus item info.
            /// </summary>
            [RepositoryItemInfo("66a4267d-29c1-49c6-9a94-a860640222fd")]
            public virtual RepoItemInfo txtDGCurrentlyRunningStatusInfo
            {
                get
                {
                    return _txtdgcurrentlyrunningstatusInfo;
                }
            }

            /// <summary>
            /// The txtAggregationCurrentlyRunning item.
            /// </summary>
            [RepositoryItem("4677c6d9-2dfe-4e15-86c2-e1ac60f07c46")]
            public virtual Ranorex.Text txtAggregationCurrentlyRunning
            {
                get
                {
                    return _txtaggregationcurrentlyrunningInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtAggregationCurrentlyRunning item info.
            /// </summary>
            [RepositoryItemInfo("4677c6d9-2dfe-4e15-86c2-e1ac60f07c46")]
            public virtual RepoItemInfo txtAggregationCurrentlyRunningInfo
            {
                get
                {
                    return _txtaggregationcurrentlyrunningInfo;
                }
            }

            /// <summary>
            /// The txtDGCompletionStatus item.
            /// </summary>
            [RepositoryItem("3004595f-b329-45aa-b366-25d3475fe811")]
            public virtual Ranorex.Text txtDGCompletionStatus
            {
                get
                {
                    return _txtdgcompletionstatusInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtDGCompletionStatus item info.
            /// </summary>
            [RepositoryItemInfo("3004595f-b329-45aa-b366-25d3475fe811")]
            public virtual RepoItemInfo txtDGCompletionStatusInfo
            {
                get
                {
                    return _txtdgcompletionstatusInfo;
                }
            }

            /// <summary>
            /// The txtAggregationCompletionStatus item.
            /// </summary>
            [RepositoryItem("2109553c-92b0-45b1-9345-b2f5ad5c1453")]
            public virtual Ranorex.Text txtAggregationCompletionStatus
            {
                get
                {
                    return _txtaggregationcompletionstatusInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtAggregationCompletionStatus item info.
            /// </summary>
            [RepositoryItemInfo("2109553c-92b0-45b1-9345-b2f5ad5c1453")]
            public virtual RepoItemInfo txtAggregationCompletionStatusInfo
            {
                get
                {
                    return _txtaggregationcompletionstatusInfo;
                }
            }

            /// <summary>
            /// The btnAggregateNow item.
            /// </summary>
            [RepositoryItem("e76743c4-523b-4dbb-aa6c-eb80898cce48")]
            public virtual Ranorex.Button btnAggregateNow
            {
                get
                {
                    return _btnaggregatenowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnAggregateNow item info.
            /// </summary>
            [RepositoryItemInfo("e76743c4-523b-4dbb-aa6c-eb80898cce48")]
            public virtual RepoItemInfo btnAggregateNowInfo
            {
                get
                {
                    return _btnaggregatenowInfo;
                }
            }

            /// <summary>
            /// The btnGOWOk item.
            /// </summary>
            [RepositoryItem("db6619de-a8c3-448e-9193-8d14f5673a7f")]
            public virtual Ranorex.Button btnGOWOk
            {
                get
                {
                    return _btngowokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnGOWOk item info.
            /// </summary>
            [RepositoryItemInfo("db6619de-a8c3-448e-9193-8d14f5673a7f")]
            public virtual RepoItemInfo btnGOWOkInfo
            {
                get
                {
                    return _btngowokInfo;
                }
            }

            /// <summary>
            /// The btnRefresh item.
            /// </summary>
            [RepositoryItem("dede8117-c9cc-4572-b1f4-7c706fe10774")]
            public virtual Ranorex.Button btnRefresh
            {
                get
                {
                    return _btnrefreshInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnRefresh item info.
            /// </summary>
            [RepositoryItemInfo("dede8117-c9cc-4572-b1f4-7c706fe10774")]
            public virtual RepoItemInfo btnRefreshInfo
            {
                get
                {
                    return _btnrefreshInfo;
                }
            }

            /// <summary>
            /// The btnApply item.
            /// </summary>
            [RepositoryItem("efff6fbd-be15-4e48-b072-07a1abf036e0")]
            public virtual Ranorex.Button btnApply
            {
                get
                {
                    return _btnapplyInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnApply item info.
            /// </summary>
            [RepositoryItemInfo("efff6fbd-be15-4e48-b072-07a1abf036e0")]
            public virtual RepoItemInfo btnApplyInfo
            {
                get
                {
                    return _btnapplyInfo;
                }
            }

            /// <summary>
            /// The txtAggregateForecastingData item.
            /// </summary>
            [RepositoryItem("73504de1-d7ad-4305-9f7d-502158b4fd56")]
            public virtual Ranorex.Text txtAggregateForecastingData
            {
                get
                {
                    return _txtaggregateforecastingdataInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtAggregateForecastingData item info.
            /// </summary>
            [RepositoryItemInfo("73504de1-d7ad-4305-9f7d-502158b4fd56")]
            public virtual RepoItemInfo txtAggregateForecastingDataInfo
            {
                get
                {
                    return _txtaggregateforecastingdataInfo;
                }
            }

            /// <summary>
            /// The txtGroomForecastingData item.
            /// </summary>
            [RepositoryItem("ac2fb595-2226-49f2-9bc1-49617e0f6e66")]
            public virtual Ranorex.Text txtGroomForecastingData
            {
                get
                {
                    return _txtgroomforecastingdataInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtGroomForecastingData item info.
            /// </summary>
            [RepositoryItemInfo("ac2fb595-2226-49f2-9bc1-49617e0f6e66")]
            public virtual RepoItemInfo txtGroomForecastingDataInfo
            {
                get
                {
                    return _txtgroomforecastingdataInfo;
                }
            }

            /// <summary>
            /// The GroomStandardMetrixAndBaseline item.
            /// </summary>
            [RepositoryItem("cb98d8c0-d2f4-4450-b009-3532ca0073e0")]
            public virtual Ranorex.Text GroomStandardMetrixAndBaseline
            {
                get
                {
                    return _groomstandardmetrixandbaselineInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The GroomStandardMetrixAndBaseline item info.
            /// </summary>
            [RepositoryItemInfo("cb98d8c0-d2f4-4450-b009-3532ca0073e0")]
            public virtual RepoItemInfo GroomStandardMetrixAndBaselineInfo
            {
                get
                {
                    return _groomstandardmetrixandbaselineInfo;
                }
            }

            /// <summary>
            /// The AggregateQueryDataInto item.
            /// </summary>
            [RepositoryItem("de5fbc57-3a2c-4f81-9e5c-abc2a430930a")]
            public virtual Ranorex.Text AggregateQueryDataInto
            {
                get
                {
                    return _aggregatequerydataintoInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AggregateQueryDataInto item info.
            /// </summary>
            [RepositoryItemInfo("de5fbc57-3a2c-4f81-9e5c-abc2a430930a")]
            public virtual RepoItemInfo AggregateQueryDataIntoInfo
            {
                get
                {
                    return _aggregatequerydataintoInfo;
                }
            }

            /// <summary>
            /// The GroomInactiveAlert item.
            /// </summary>
            [RepositoryItem("3fb2ebda-cce5-4ac4-b199-394653d2665c")]
            public virtual Ranorex.Text GroomInactiveAlert
            {
                get
                {
                    return _groominactivealertInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The GroomInactiveAlert item info.
            /// </summary>
            [RepositoryItemInfo("3fb2ebda-cce5-4ac4-b199-394653d2665c")]
            public virtual RepoItemInfo GroomInactiveAlertInfo
            {
                get
                {
                    return _groominactivealertInfo;
                }
            }

            /// <summary>
            /// The GroomPrescriptiveAnalysis item.
            /// </summary>
            [RepositoryItem("75d1eb55-600b-44fc-ac08-9fc009910a61")]
            public virtual Ranorex.Text GroomPrescriptiveAnalysis
            {
                get
                {
                    return _groomprescriptiveanalysisInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The GroomPrescriptiveAnalysis item info.
            /// </summary>
            [RepositoryItemInfo("75d1eb55-600b-44fc-ac08-9fc009910a61")]
            public virtual RepoItemInfo GroomPrescriptiveAnalysisInfo
            {
                get
                {
                    return _groomprescriptiveanalysisInfo;
                }
            }

            /// <summary>
            /// The AggregaionOnceDailyAt item.
            /// </summary>
            [RepositoryItem("0b029e11-c7a7-423e-a20e-586adb6c05cf")]
            public virtual Ranorex.Text AggregaionOnceDailyAt
            {
                get
                {
                    return _aggregaiononcedailyatInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AggregaionOnceDailyAt item info.
            /// </summary>
            [RepositoryItemInfo("0b029e11-c7a7-423e-a20e-586adb6c05cf")]
            public virtual RepoItemInfo AggregaionOnceDailyAtInfo
            {
                get
                {
                    return _aggregaiononcedailyatInfo;
                }
            }

            /// <summary>
            /// The GroomSessionsQueries item.
            /// </summary>
            [RepositoryItem("8d4e12ef-38a7-4191-8a37-9ebf6461b612")]
            public virtual Ranorex.Text GroomSessionsQueries
            {
                get
                {
                    return _groomsessionsqueriesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The GroomSessionsQueries item info.
            /// </summary>
            [RepositoryItemInfo("8d4e12ef-38a7-4191-8a37-9ebf6461b612")]
            public virtual RepoItemInfo GroomSessionsQueriesInfo
            {
                get
                {
                    return _groomsessionsqueriesInfo;
                }
            }

            /// <summary>
            /// The GroomChangeLog item.
            /// </summary>
            [RepositoryItem("ee387910-4f33-4868-8ab2-40e6f12661af")]
            public virtual Ranorex.Text GroomChangeLog
            {
                get
                {
                    return _groomchangelogInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The GroomChangeLog item info.
            /// </summary>
            [RepositoryItemInfo("ee387910-4f33-4868-8ab2-40e6f12661af")]
            public virtual RepoItemInfo GroomChangeLogInfo
            {
                get
                {
                    return _groomchangelogInfo;
                }
            }

            /// <summary>
            /// The GroomingOnceDailyAt item.
            /// </summary>
            [RepositoryItem("1c880ec9-e930-4ccc-ace1-fd289843f3a2")]
            public virtual Ranorex.Text GroomingOnceDailyAt
            {
                get
                {
                    return _groomingoncedailyatInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The GroomingOnceDailyAt item info.
            /// </summary>
            [RepositoryItemInfo("1c880ec9-e930-4ccc-ace1-fd289843f3a2")]
            public virtual RepoItemInfo GroomingOnceDailyAtInfo
            {
                get
                {
                    return _groomingoncedailyatInfo;
                }
            }
        }

        /// <summary>
        /// The SQLdmDCAppFolder folder.
        /// </summary>
        [RepositoryFolder("256ebeeb-693e-428e-bf76-2222c9b118b1")]
        public partial class SQLdmDCAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _propertiesInfo;
            RepoItemInfo _deleteInfo;
            RepoItemInfo _openInfo;
            RepoItemInfo _manageserversInfo;
            RepoItemInfo _newitemInfo;

            /// <summary>
            /// Creates a new SQLdmDC  folder.
            /// </summary>
            public SQLdmDCAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SQLdmDC", "/contextmenu[@processname='SQLdmDesktopClient']", parentFolder, 30000, null, true, "256ebeeb-693e-428e-bf76-2222c9b118b1", "")
            {
                _propertiesInfo = new RepoItemInfo(this, "Properties", ".//contextmenu/menuitem[@accessiblename='Properties...']", 30000, null, "9944a558-0d7d-4d1e-b2ad-5bc81b268080");
                _deleteInfo = new RepoItemInfo(this, "Delete", ".//contextmenu/menuitem[@accessiblename='Delete']", 30000, null, "47199315-3413-4383-b5c3-3c1c21110ecb");
                _openInfo = new RepoItemInfo(this, "Open", ".//menuitem[@accessiblename='Open']", 30000, null, "4e4d4aee-f5d6-4d14-bb89-587099d448e4");
                _manageserversInfo = new RepoItemInfo(this, "ManageServers", ".//menuitem[@accessiblename='Manage Servers...']", 30000, null, "091c8036-40d2-4eb7-abf5-8fbca6ea94d7");
                _newitemInfo = new RepoItemInfo(this, "NewItem", "element", 30000, null, "a6c44018-3c78-458d-8cd3-df014c38b33c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("256ebeeb-693e-428e-bf76-2222c9b118b1")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("256ebeeb-693e-428e-bf76-2222c9b118b1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Properties item.
            /// </summary>
            [RepositoryItem("9944a558-0d7d-4d1e-b2ad-5bc81b268080")]
            public virtual Ranorex.MenuItem Properties
            {
                get
                {
                    return _propertiesInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Properties item info.
            /// </summary>
            [RepositoryItemInfo("9944a558-0d7d-4d1e-b2ad-5bc81b268080")]
            public virtual RepoItemInfo PropertiesInfo
            {
                get
                {
                    return _propertiesInfo;
                }
            }

            /// <summary>
            /// The Delete item.
            /// </summary>
            [RepositoryItem("47199315-3413-4383-b5c3-3c1c21110ecb")]
            public virtual Ranorex.MenuItem Delete
            {
                get
                {
                    return _deleteInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Delete item info.
            /// </summary>
            [RepositoryItemInfo("47199315-3413-4383-b5c3-3c1c21110ecb")]
            public virtual RepoItemInfo DeleteInfo
            {
                get
                {
                    return _deleteInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("4e4d4aee-f5d6-4d14-bb89-587099d448e4")]
            public virtual Ranorex.MenuItem Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("4e4d4aee-f5d6-4d14-bb89-587099d448e4")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The ManageServers item.
            /// </summary>
            [RepositoryItem("091c8036-40d2-4eb7-abf5-8fbca6ea94d7")]
            public virtual Ranorex.MenuItem ManageServers
            {
                get
                {
                    return _manageserversInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ManageServers item info.
            /// </summary>
            [RepositoryItemInfo("091c8036-40d2-4eb7-abf5-8fbca6ea94d7")]
            public virtual RepoItemInfo ManageServersInfo
            {
                get
                {
                    return _manageserversInfo;
                }
            }

            /// <summary>
            /// The NewItem item.
            /// </summary>
            [RepositoryItem("a6c44018-3c78-458d-8cd3-df014c38b33c")]
            public virtual Ranorex.Unknown NewItem
            {
                get
                {
                    return _newitemInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The NewItem item info.
            /// </summary>
            [RepositoryItemInfo("a6c44018-3c78-458d-8cd3-df014c38b33c")]
            public virtual RepoItemInfo NewItemInfo
            {
                get
                {
                    return _newitemInfo;
                }
            }
        }

        /// <summary>
        /// The DeleteConfirmWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("5ce7a0a5-8af2-4e55-bcc3-0bc83cf5fb2f")]
        public partial class DeleteConfirmWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnconfirmnoInfo;
            RepoItemInfo _btnconfirmyesInfo;
            RepoItemInfo _btnconfirmcancelInfo;

            /// <summary>
            /// Creates a new DeleteConfirmWindow  folder.
            /// </summary>
            public DeleteConfirmWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DeleteConfirmWindow", "/form[@controlname='ExceptionMessageBoxForm']", parentFolder, 30000, null, true, "5ce7a0a5-8af2-4e55-bcc3-0bc83cf5fb2f", "")
            {
                _btnconfirmnoInfo = new RepoItemInfo(this, "btnConfirmNo", ".//container[@controlname='pnlForm']/?/?/button[@controlname='button2']", 30000, null, "d2967b2a-1bdd-4a46-8323-14550dbe9612");
                _btnconfirmyesInfo = new RepoItemInfo(this, "btnConfirmYes", ".//container[@controlname='pnlForm']/?/?/button[@controlname='button1']", 30000, null, "9f1efe92-29ff-41a3-a34d-379c3d241c96");
                _btnconfirmcancelInfo = new RepoItemInfo(this, "btnConfirmCancel", ".//container[@controlname='pnlForm']/?/?/button[@controlname='button3']", 30000, null, "b863612d-ecc5-4e30-a0c0-92406ac6cc7f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5ce7a0a5-8af2-4e55-bcc3-0bc83cf5fb2f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5ce7a0a5-8af2-4e55-bcc3-0bc83cf5fb2f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnConfirmNo item.
            /// </summary>
            [RepositoryItem("d2967b2a-1bdd-4a46-8323-14550dbe9612")]
            public virtual Ranorex.Button btnConfirmNo
            {
                get
                {
                    return _btnconfirmnoInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnConfirmNo item info.
            /// </summary>
            [RepositoryItemInfo("d2967b2a-1bdd-4a46-8323-14550dbe9612")]
            public virtual RepoItemInfo btnConfirmNoInfo
            {
                get
                {
                    return _btnconfirmnoInfo;
                }
            }

            /// <summary>
            /// The btnConfirmYes item.
            /// </summary>
            [RepositoryItem("9f1efe92-29ff-41a3-a34d-379c3d241c96")]
            public virtual Ranorex.Button btnConfirmYes
            {
                get
                {
                    return _btnconfirmyesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnConfirmYes item info.
            /// </summary>
            [RepositoryItemInfo("9f1efe92-29ff-41a3-a34d-379c3d241c96")]
            public virtual RepoItemInfo btnConfirmYesInfo
            {
                get
                {
                    return _btnconfirmyesInfo;
                }
            }

            /// <summary>
            /// The btnConfirmCancel item.
            /// </summary>
            [RepositoryItem("b863612d-ecc5-4e30-a0c0-92406ac6cc7f")]
            public virtual Ranorex.Button btnConfirmCancel
            {
                get
                {
                    return _btnconfirmcancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnConfirmCancel item info.
            /// </summary>
            [RepositoryItemInfo("b863612d-ecc5-4e30-a0c0-92406ac6cc7f")]
            public virtual RepoItemInfo btnConfirmCancelInfo
            {
                get
                {
                    return _btnconfirmcancelInfo;
                }
            }
        }

        /// <summary>
        /// The ManageServersDialogAppFolder folder.
        /// </summary>
        [RepositoryFolder("5cc11763-76f2-47b0-a946-09f66e3b0212")]
        public partial class ManageServersDialogAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnmsaddInfo;
            RepoItemInfo _btnmsokInfo;
            RepoItemInfo _btnapplyInfo;

            /// <summary>
            /// Creates a new ManageServersDialog  folder.
            /// </summary>
            public ManageServersDialogAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ManageServersDialog", "//form[@controlname='ManageServersDialog']", parentFolder, 30000, null, true, "5cc11763-76f2-47b0-a946-09f66e3b0212", "")
            {
                _btnmsaddInfo = new RepoItemInfo(this, "btnMSAdd", ".//button[@controlname='addButton']", 30000, null, "9741e07b-1e1c-49fc-9680-98babfa16cd4");
                _btnmsokInfo = new RepoItemInfo(this, "btnMSOk", ".//button[@controlname='okButton']", 30000, null, "286fe2d7-13e5-47b6-a1f6-5c58372f4591");
                _btnapplyInfo = new RepoItemInfo(this, "btnApply", ".//button[@controlname='applyButton']", 30000, null, "944b2866-b7c3-4f59-8b33-fc102c15cf20");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5cc11763-76f2-47b0-a946-09f66e3b0212")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5cc11763-76f2-47b0-a946-09f66e3b0212")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnMSAdd item.
            /// </summary>
            [RepositoryItem("9741e07b-1e1c-49fc-9680-98babfa16cd4")]
            public virtual Ranorex.Button btnMSAdd
            {
                get
                {
                    return _btnmsaddInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnMSAdd item info.
            /// </summary>
            [RepositoryItemInfo("9741e07b-1e1c-49fc-9680-98babfa16cd4")]
            public virtual RepoItemInfo btnMSAddInfo
            {
                get
                {
                    return _btnmsaddInfo;
                }
            }

            /// <summary>
            /// The btnMSOk item.
            /// </summary>
            [RepositoryItem("286fe2d7-13e5-47b6-a1f6-5c58372f4591")]
            public virtual Ranorex.Button btnMSOk
            {
                get
                {
                    return _btnmsokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnMSOk item info.
            /// </summary>
            [RepositoryItemInfo("286fe2d7-13e5-47b6-a1f6-5c58372f4591")]
            public virtual RepoItemInfo btnMSOkInfo
            {
                get
                {
                    return _btnmsokInfo;
                }
            }

            /// <summary>
            /// The btnApply item.
            /// </summary>
            [RepositoryItem("944b2866-b7c3-4f59-8b33-fc102c15cf20")]
            public virtual Ranorex.Button btnApply
            {
                get
                {
                    return _btnapplyInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnApply item info.
            /// </summary>
            [RepositoryItemInfo("944b2866-b7c3-4f59-8b33-fc102c15cf20")]
            public virtual RepoItemInfo btnApplyInfo
            {
                get
                {
                    return _btnapplyInfo;
                }
            }
        }

        /// <summary>
        /// The AddServersWizardDialogAppFolder folder.
        /// </summary>
        [RepositoryFolder("b2b42fbb-af61-4285-9c7b-5b6cad72d3d6")]
        public partial class AddServersWizardDialogAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnaswnextInfo;
            RepoItemInfo _txtavailableserversInfo;
            RepoItemInfo _btnsstmaddInfo;
            RepoItemInfo _btnasfinishInfo;

            /// <summary>
            /// Creates a new AddServersWizardDialog  folder.
            /// </summary>
            public AddServersWizardDialogAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AddServersWizardDialog", "//form[@controlname='AddServersWizard']", parentFolder, 30000, null, true, "b2b42fbb-af61-4285-9c7b-5b6cad72d3d6", "")
            {
                _btnaswnextInfo = new RepoItemInfo(this, "btnASWNext", ".//button[@controlname='xb0664f16ddb81b92']", 30000, null, "24ca5951-8923-467d-8112-25de8ee936b3");
                _txtavailableserversInfo = new RepoItemInfo(this, "txtAvailableServers", ".//text[@controlname='adhocInstancesTextBox']/text[@accessiblerole='Text']", 30000, null, "57fda492-779c-4c57-a4b9-ddd17f2e4f64");
                _btnsstmaddInfo = new RepoItemInfo(this, "btnSSTMAdd", ".//container[@controlname='wizardFramework']/?/?/button[@controlname='addInstancesButton']", 30000, null, "7adfd195-640a-4568-9b57-76df8cd68b00");
                _btnasfinishInfo = new RepoItemInfo(this, "btnASFinish", ".//button[@controlname='xb0664f16ddb81b92']", 30000, null, "7574ddd6-a524-4b54-8fef-b97f4402bcb3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b2b42fbb-af61-4285-9c7b-5b6cad72d3d6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b2b42fbb-af61-4285-9c7b-5b6cad72d3d6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnASWNext item.
            /// </summary>
            [RepositoryItem("24ca5951-8923-467d-8112-25de8ee936b3")]
            public virtual Ranorex.Button btnASWNext
            {
                get
                {
                    return _btnaswnextInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnASWNext item info.
            /// </summary>
            [RepositoryItemInfo("24ca5951-8923-467d-8112-25de8ee936b3")]
            public virtual RepoItemInfo btnASWNextInfo
            {
                get
                {
                    return _btnaswnextInfo;
                }
            }

            /// <summary>
            /// The txtAvailableServers item.
            /// </summary>
            [RepositoryItem("57fda492-779c-4c57-a4b9-ddd17f2e4f64")]
            public virtual Ranorex.Text txtAvailableServers
            {
                get
                {
                    return _txtavailableserversInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtAvailableServers item info.
            /// </summary>
            [RepositoryItemInfo("57fda492-779c-4c57-a4b9-ddd17f2e4f64")]
            public virtual RepoItemInfo txtAvailableServersInfo
            {
                get
                {
                    return _txtavailableserversInfo;
                }
            }

            /// <summary>
            /// The btnSSTMAdd item.
            /// </summary>
            [RepositoryItem("7adfd195-640a-4568-9b57-76df8cd68b00")]
            public virtual Ranorex.Button btnSSTMAdd
            {
                get
                {
                    return _btnsstmaddInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnSSTMAdd item info.
            /// </summary>
            [RepositoryItemInfo("7adfd195-640a-4568-9b57-76df8cd68b00")]
            public virtual RepoItemInfo btnSSTMAddInfo
            {
                get
                {
                    return _btnsstmaddInfo;
                }
            }

            /// <summary>
            /// The btnASFinish item.
            /// </summary>
            [RepositoryItem("7574ddd6-a524-4b54-8fef-b97f4402bcb3")]
            public virtual Ranorex.Button btnASFinish
            {
                get
                {
                    return _btnasfinishInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnASFinish item info.
            /// </summary>
            [RepositoryItemInfo("7574ddd6-a524-4b54-8fef-b97f4402bcb3")]
            public virtual RepoItemInfo btnASFinishInfo
            {
                get
                {
                    return _btnasfinishInfo;
                }
            }
        }

        /// <summary>
        /// The ExceptionMessageBoxFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("9999567a-03cb-4278-91cf-451b5ffba7d6")]
        public partial class ExceptionMessageBoxFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnmsyesInfo;

            /// <summary>
            /// Creates a new ExceptionMessageBoxForm  folder.
            /// </summary>
            public ExceptionMessageBoxFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ExceptionMessageBoxForm", "//form[@controlname='ExceptionMessageBoxForm']", parentFolder, 30000, null, true, "9999567a-03cb-4278-91cf-451b5ffba7d6", "")
            {
                _btnmsyesInfo = new RepoItemInfo(this, "btnMSYes", ".//container[@controlname='pnlButtons']/button[@controlname='button1']", 30000, null, "6caf09c9-6eb6-407b-a6a6-1ec3b557bf6a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9999567a-03cb-4278-91cf-451b5ffba7d6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9999567a-03cb-4278-91cf-451b5ffba7d6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnMSYes item.
            /// </summary>
            [RepositoryItem("6caf09c9-6eb6-407b-a6a6-1ec3b557bf6a")]
            public virtual Ranorex.Button btnMSYes
            {
                get
                {
                    return _btnmsyesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnMSYes item info.
            /// </summary>
            [RepositoryItemInfo("6caf09c9-6eb6-407b-a6a6-1ec3b557bf6a")]
            public virtual RepoItemInfo btnMSYesInfo
            {
                get
                {
                    return _btnmsyesInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}